# -*- coding: utf-8 -*-
"""
/***************************************************************************
 posg
                                 A QGIS plugin
 Complemento de pruebas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-30
        copyright            : (C) 2026 by Hernan Camelo
        email                : idu0821272@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load posg class from file posg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .modulo_POSG import posg
    return posg(iface)
