# -*- coding: utf-8 -*-
"""
/***************************************************************************
 posgDockWidget
                                 A QGIS plugin
 Complemento de pruebas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Hernan Camelo
        email                : idu0821272@usal.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject, QgsVectorLayer,QgsField, QgsFeature, QgsGeometry,QgsPointXY
from PyQt5.QtCore import QVariant


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'modulo_POSG_dockwidget_base.ui'))


class posgDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(posgDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.selector_archivos.setFilter("Archivos csv(*.csv)") 
        self.btn_cargar.clicked.connect(self.cargar_datos)
        self.btn_crearcapa.clicked.connect(self.crear_capa)


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def cargar_datos(self,event):
        ruta=str(self.selector_archivos.filePath())
        with open(ruta,'r') as leer_csv: #abro el archivo para leer
            lineas=leer_csv.read().splitlines()#Separo por lineas
        contar=0
        for linea in lineas:
            if contar>0:
                campos=linea.split(';')
                self.tabla.insertRow(self.tabla.rowCount())
                self.tabla.setItem(self.tabla.rowCount()-1,0,QtWidgets.QTableWidgetItem((campos[1])))
                self.tabla.setItem(self.tabla.rowCount() - 1, 1, QtWidgets.QTableWidgetItem((campos[2])))
                self.tabla.setItem(self.tabla.rowCount() - 1, 2, QtWidgets.QTableWidgetItem((campos[5])))
                self.tabla.setItem(self.tabla.rowCount() - 1, 3, QtWidgets.QTableWidgetItem((campos[4])))
            contar=contar+1

    def crear_capa(self,event):
        vlayer = QgsVectorLayer('Point?crs=EPSG:4326', 'Paradas Autobus', 'memory')
        provider = vlayer.dataProvider()
        provider.addAttributes([QgsField('Codigo_Parada', QVariant.String), QgsField('Nombre_Parada', QVariant.String)])
        vlayer.updateFields()
        #Hasta aquí preparo los valores de la capa
        #Introduzco el primer elemento de la tabla
        for fila in range(0,self.tabla.rowCount()-1):
            f = QgsFeature()
            f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(float(self.tabla.item(fila,2).text()),float(self.tabla.item(fila,3).text()))))
            f.setAttributes([self.tabla.item(fila,0).text(),self.tabla.item(fila,1).text()])
            provider.addFeature(f)
        #Añado la capa al mapa
        vlayer.updateExtents()
        QgsProject.instance().addMapLayer(vlayer)
