# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModuloProyecto
                                 A QGIS plugin
 Complemento proyecto Máster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-01
        copyright            : (C) 2026 by Hernan Dario Camelo Pinzon
        email                : idu082127@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ModuloProyecto class from file ModuloProyecto.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .modulo_proyecto_posg import ModuloProyecto
    return ModuloProyecto(iface)
